### ISSUE TITLE
Update to sveltekit websockets article for new 1.0 skeleton default

### ISSUE THREAD

**Issue by luiderek** [mattcroat/joy-of-code#101]
https://joyofcode.xyz/using-websockets-with-sveltekit

So this article no longer works out of the box, for either the dev / build with the error: 
`Error: Unexpected option config.kit.vite`

Based on my past flailing around to figure out SSL certs, I believe the code can just be shuffled around from svelte.config to vite.config, in order to retain the intended effects. 

within `vite.config.js`
```
import { sveltekit } from '@sveltejs/kit/vite';
import { Server } from 'socket.io'

export const webSocketServer = {
	name: 'webSocketServer',
	configureServer(server) {
		const io = new Server(server.httpServer)

		io.on('connection', (socket) => {
			socket.emit('eventFromServer', 'Hello, World 👋')
		})
	},
}

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit(), webSocketServer]
};

export default config;
```

and within `svelte.config.js`
just swapping the adapter from @sveltejs/adapter-auto to @sveltejs/adapter-node

thanks for the guide by the way!

**Comment by mattcroat** [comment]
Yeah, I have to update it.

Thank you! 🙏
