### ISSUE TITLE
Re: Working With Forms In SvelteKit

### ISSUE THREAD

**Issue by vorian77** [mattcroat/joy-of-code#118]
In the progressive enhance section, you have the paragraph:

> The point is not that your site should work without JavaScript but before it because JavaScript can fail loading for various reasons and this is what makes your app more resilient — instead of relying on JavaScript you can use it to progressive enhance the form and the user experience when JavaScript is available on the page.

I thought I'd share that it didn't read quite clearly to me.

Thanks for all your work in educating the world on programming!

**Comment by mattcroat** [comment]
Yeah, that's not great!

> [JavaScript can fail to load for many reasons](https://www.kryogenix.org/code/browser/everyonehasjs.html) but I'm not advocating that every site should work **without** JavaScript and should instead work **before** JavaScript is loaded on the page. This approach to development makes your app more resilient and you can use JavaScript once it's available to improve the user experience using progressive enhancement as intended.

How do you feel about that @vorian77?

**Comment by vorian77** [comment]
Sounds good to me, thanks again!On Apr 23, 2023, at 3:52 PM, Matia ***@***.***> wrote:﻿
Yeah, that's not great!

JavaScript can fail to load for many reasons but I'm not advocating that every site should work without JavaScript and should instead work before JavaScript is loaded on the page. This approach to development makes your app more resilient and you can use JavaScript once it's available to improve the user experience using progressive enhancement as intended.

How do you feel about that @vorian77?
