### ISSUE TITLE
rendering strategy clarification

### ISSUE THREAD

**Issue by ITwrx** [mattcroat/joy-of-code#125]
hi, 

I've never been clear on how this works and your article linked below gets close, but i've never seen it spelled out completely. 

https://joyofcode.xyz/learn-how-sveltekit-works#client-side-rendering

> As I previously mentioned when you load a page for the first time it’s going to use server-side rendering but after the client gets initialized subsequent navigations use client-side navigation but you can still view the page source.

subsequent navs to **what**, **specifically**? the same page or all pages?
IOW, subsequent navs only to pages already SSR'd use client side navigation just to save resources and time? or after **any** page is SSR'd for the first time **all** the pages are downloaded to the client, so **all** subsequent navs to **any pages** are CSR'd? 

thanks

**Comment by ITwrx** [comment]
snarf! i just saw you have Discussions enabled, so i probably could have asked there...

**Comment by mattcroat** [comment]
@ITwrx When the client-side router loads your SvelteKit app behaves like a regular single page application (SPA) meaning it's client-side rendered using JavaScript but if you refresh the page or visit the page for the first time it's server-side rendered.

**Comment by ITwrx** [comment]
thanks! so it sounds like it's the first one: 

> IOW, subsequent navs only to pages already SSR'd use client side navigation...

so, if i'm correct, it might be clearer if your post said something like:

> As I previously mentioned, when you load a page for the first time, it’s going to use server-side rendering, but after the client gets initialized, subsequent navigations to that same page (and other previously SSR'd pages)  use client-side navigation, but you can still view the page source.
