### ISSUE TITLE
Wrong file name?

### ISSUE THREAD

**Issue by RobinKohrs** [mattcroat/joy-of-code#129]
Thank you so much for all these explanations! I'm not really sure, but I think this might be a wrong filename? And should actually be a svelte route?!

![image](https://user-images.githubusercontent.com/118171921/236632555-55ec7911-6c5a-4e12-a0a7-c7e4d059099f.png)

Again, thanks so much!

**Comment by mattcroat** [comment]
Thank you! 😄

**Comment by RobinKohrs** [comment]
Nothing to thank for haha! Thank you:) I started my website, just because of this video;)
