### ISSUE TITLE
add links to Rich Harris's version of emoji matching game

### ISSUE THREAD

**Issue by baderj** [mattcroat/joy-of-code#138]
Your made a post (and corresponding [YouTube video](https://www.youtube.com/watch?v=w2q9caYXgkg)) on [an emoji matching game](https://github.com/mattcroat/joy-of-code/tree/main/posts/svelte-matching-game/svelte-matching-game.md).

Rich Harris's, the creator of Svelte, built a extremely similar [emoji matching game](https://ematchi.vercel.app/) that he built for a paywalled [Frontend Matters](https://frontendmasters.com) course.

I think adding some links to his version might be valuable to your watchers / readers:

- https://ematchi.vercel.app/
- https://github.com/Rich-Harris/ematchi
- https://frontendmasters.com/courses/svelte-v2/

**Comment by mattcroat** [comment]
That's a good idea.
