### ISSUE TITLE
CSS Z-index  Issue on Preferences, Categories and Table of Contents Section

### ISSUE THREAD

**Issue by mithi** [mattcroat/joy-of-code#156]
Hi! 

Thanks for putting out all  these amazing content on Svelte, such a valuable resource!

I'm not sure if it's intended or not but  I noticed that the border of the `Categories` Dialog and `Preference` Dialog gets cut off by the `Table of Contents` section which could be fixed by adding `z-index: 10`. 

# Current: 
<img width="1175" alt="Screen Shot 2023-11-21 at 12 01 56 PM" src="https://github.com/mattcroat/joy-of-code/assets/1670421/f573cfe7-6324-49cd-b158-99ad0f5e61d5">

<img width="1137" alt="Screen Shot 2023-11-21 at 12 04 23 PM" src="https://github.com/mattcroat/joy-of-code/assets/1670421/738dad5c-5428-4eff-9391-b5fca4948398">

# Modified: (with `z-index: 10` added) 
<img width="1176" alt="Screen Shot 2023-11-21 at 11 53 16 AM" src="https://github.com/mattcroat/joy-of-code/assets/1670421/92e03928-3e57-4d80-9c25-1a0ab07fe91b">
<img width="1140" alt="Screen Shot 2023-11-21 at 11 54 33 AM" src="https://github.com/mattcroat/joy-of-code/assets/1670421/62e6a5bd-8b76-4e74-bd8a-c40f69f0406d">

Just thought you should know in case you weren't aware of this issue. 
If this is intended behavior, feel free to just close this issue as resolved. Thanks!

**Comment by mattcroat** [comment]
@mithi Thank you, I fixed it! 😄
