### ISSUE TITLE
BUG: site search broken?

### ISSUE THREAD

**Issue by markuskobler** [mattcroat/joy-of-code#174]
👋 Matia. Fan of your Svelte content (keep it up!).

I was just checking out your site search article and noticed that its not working using latest chrome and safari on desktop at least.

<img width="1386" alt="Screenshot 2024-07-01 at 2 04 17 PM" src="https://github.com/mattcroat/joy-of-code/assets/61794/4a4db154-2632-4024-a3c4-f92e16b95b2d">

I did not have time to debug the issue unfortunately but it might be related to the following warnings in the console.

```
The resource https://w-staticblitz.com/fetch.worker.70dbe416.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by mattcroat** [comment]
@markuskobler it works for me on the latest version of Chrome (126.0.6478.126) and the warnings in the console are from the StackBlitz REPL and not me

![image](https://github.com/mattcroat/joy-of-code/assets/38083522/fa983f65-f057-42e9-9044-b19d94eaa54f)
