### ISSUE TITLE
Issue: Flickering on scrolling down

### ISSUE THREAD

**Issue by adambelko** [mattcroat/joy-of-code#178]
When trying to scroll down on a pages with less content (in terms of their height), like "About" or "React", the flickering issue appears.

It only happens on my big 28” monitor using Chrome.
There's no issues on smaller screens or using Safari.

Recording of my screen: 
https://github.com/user-attachments/assets/1cc7a749-51ba-43c9-b234-e53b538c849b

**Comment by mattcroat** [comment]
I can't reproduce it
