### ISSUE TITLE
rehypeUnwrapImages not working

### ISSUE THREAD

**Issue by Mingx94** [mattcroat/joy-of-code#180]
Due to the `searchAndReplace` function in `lib/markdown/index.js`, the markdown will contain HTML code, which is treated as raw text in `rehypeUnwrapImages` when checking `containsImage`.

Maybe using [rehype-raw](https://github.com/rehypejs/rehype-raw), as mentioned in the [rehype-remark documentation](https://github.com/remarkjs/remark-rehype?tab=readme-ov-file#when-should-i-use-this), to parse raw HTML into an AST first.

<img width="800" alt="screenshot" src="https://github.com/user-attachments/assets/8ebf4e8f-21da-4d2b-a02f-f724fac25d71">

**Comment by mattcroat** [comment]
I missed that, thank you! 😄

I'm going to use CSS instead:

```css
p:has(img) {
  display: contents;
}
```
