### ISSUE TITLE
sveltekit-markdown-blog: formatDate function question

### ISSUE THREAD

**Issue by y0nei** [mattcroat/joy-of-code#182]
Why is the dash conversion needed for Safari in the formatDate function?
The input date is already a valid `Date` object if i use `Date` instead of `string`, and date will get transformed server side by default.

```diff
-export function formatDate(date: string, dateStyle: DateStyle = 'medium', locales = 'en') {
+export function formatDate(date: Date, dateStyle: DateStyle = 'medium', locales = 'en') {
```
```ts
export function formatDate(...) {
	// Safari is mad about dashes in the date
	const dateToFormat = new Date(date.replaceAll('-', '/'))
	...
}
```

**Comment by mattcroat** [comment]
I'm passing a `string` from Markdown so it's not a `Date` and Safari from what I remember doesn't support the `-` separator for dates and throws an error the last time I tried it
