### ISSUE TITLE
In "Create a Coding Sandbox" post the example doesn't work

### ISSUE THREAD

**Issue by Programmer005** [mattcroat/joy-of-code#19]
![image](https://user-images.githubusercontent.com/77259664/128452629-bf5c2384-b9b2-4c75-a7c1-840e3b47cd60.png)

**Comment by mattcroat** [comment]
I had a look and unfortunately it's out of my control since the Skypack import for [monaco-editor](https://www.skypack.dev/view/monaco-editor) isn't working. :pensive:
