### ISSUE TITLE
Fix local storage old keys

### ISSUE THREAD

**Issue by shah1012** [mattcroat/joy-of-code#38]
If users who have used your site before you switched to sveltekit try to open the site again (chrome) it breaks. This was due to old local storage key values which tampered the setting 

old keys such as theme, charka-ui-theme 

Proof:
![unknown](https://user-images.githubusercontent.com/69828183/173148105-343a89b7-38e2-44d5-bc9a-118a71a87b3b.png)

**Comment by mattcroat** [comment]
Thank you!

I'm aware of the issue and have an idea for a fix. 😄
