### ISSUE TITLE
sticky navbar

### ISSUE THREAD

**Issue by Alexander01000** [mattcroat/joy-of-code#50]
Hey there :wave: 

I think the nav bar should be sticky i.e with fixed position property on! Why I think this is because when I'm somewhere in the middle of the page and if I have to change theme or font width or something I need to scroll to the top and change it. It's kind of time-consuming and also I get lost when I try to find where I left. I tried to change CSS through dev tools and the text Joy Of Code interferes with the other content on the page but settings and Categories seem perfect! So, I would recommend hiding the Joy Of Code text when the user scrolls down but the rest of the 2 buttons should be visible! By the way, this is my first issue ever opened on Github, so if I did something wrong, I apologize In advance.

Thanks

**Comment by mattcroat** [comment]
I agree! I'm going to add it when I have more time because it's more complicated than using `position: sticky` because of how it's implemented.

Congrats on your first issue! 🎉 I should probably enable GitHub Discussions for these sort of things.

Thank you!

**Comment by Alexander01000** [comment]
btw position:fixed; width:80% or how much u want with some high z-index value and top :4px or whatever value u like
works like a boss...
i tried using position : sticky but navbar behaved very weird.
well at the end its all up to u
