### ISSUE TITLE
CORS Error within sandbox article.

### ISSUE THREAD

**Issue by DelphiCoder** [mattcroat/joy-of-code#7]
Your article looks very interesting regarding sandboxing.

I found that the standalone babel pulled from skypack.dev generates a CORS error if you use Chrome as the browser.  You have to go to developer tools, to see the error.  But you can tell that the code on the article's page doesn't work on it's own.  Anyway Chrome will give you a lot of these while viewing your article:

`Access to script at 'https://cdn.skypack.dev/new/@babel/standalone@v7.13.17/dist=es2020' javascriptsandbox.netlify.app/:10 from origin 'https://javascriptsandbox.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

So, I went with Microsoft Edge and didn't get a CORS error, but instead saw many other errors including:

`Uncaught Error: [Package Error] standalone@v7.13.17-r2ZHbBcV4DWOrHib0Crm:13
  "@babel/standalone@v7.13.17" could not be built. 
    at standalone@v7.13.17-r2ZHbBcV4DWOrHib0Crm:13`

I have another browser (open source) that I only rarely use called "Pale Moon" and it generates the following error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.skypack.dev/new/@babel/standalone@v7.13.17/dist=es2017. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Argh!!!**, I figured you must of used a Mac to develop that page.  So I fired up mine and Apple's Safari generated errors like:

"SyntaxError: Importing binding name {transform} is not found" and 
"Error: [Package Error] @babel/standalone@v7.13.17 could not be built" and a message about an invalid escaped character for unicode within a regular expression.

So if the page worked some time ago, it doesn't work now.  But I sure wish it did as sandboxing is a topic not discussed much.

Thank you....

**Comment by mattcroat** [comment]
The CORS issue is caused when you're not using the HTTP protocol, but the file protocol. This is the explanation from the post.

>  The only thing required is the Live Server extension for VS Code so you can start a development server because otherwise it won't work due to the limitations of using the file protocol.

I resolved the main issue which was `@babel/standalone` not working using native JavaScript modules. I expect it to get resolved since it's not the intended behavior. I included a note at the start of the article that requires simple changes to make it work, and I've fixed the example.

Thanks for your feedback :+1:
