### ISSUE TITLE
svelte-todo-app markdown not being properly processed?

### ISSUE THREAD

**Issue by voodoo** [mattcroat/joy-of-code#81]
using: windows edge

Issue parsing the markdown from your todo-app tutorial. ? 

https://joyofcode.xyz/svelte-todo-app

https://github.com/mattcroat/joy-of-code/blob/main/posts/svelte-todo-app/svelte-todo-app.md

The css is not being properly 'encoded'.

![image](https://user-images.githubusercontent.com/23097/188697074-dad2101e-bae6-4bc3-bf31-e942ea01320f.png)

really great tutorial!

**Comment by mattcroat** [comment]
I figured it was a formatting issue and resolved the problem — you can use [discussions](https://github.com/mattcroat/joy-of-code/discussions) to report issues related to posts in the future.

Thank you! 😄
